services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    Acme\Bundle\SalesDocumentBundle\Controller\:
        resource: '../../Controller/'
        tags: ['controller.service_arguments']
    
    Acme\Bundle\SalesDocumentBundle\Controller\Frontend\SalesDocumentController:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@oro_attachment.file_manager'
        tags:
            - { name: controller.service_arguments }
    
    Acme\Bundle\SalesDocumentBundle\Layout\DataProvider\SalesDocumentsDataProvider:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.token_storage'
        tags:
            - { name: layout.data_provider, alias: acme_sales_documents }
            
    acme_sales_document.layout_data_provider.current_user:
        class: Acme\Bundle\SalesDocumentBundle\Layout\DataProvider\CurrentUserProvider
        arguments:
            - '@security.token_storage'
        tags:
            - { name: layout.data_provider, alias: acme_current_user }
    
    Acme\Bundle\SalesDocumentBundle\Command\GenerateExampleSalesDocumentsCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'
        tags:
            - { name: console.command }
            
    Acme\Bundle\SalesDocumentBundle\EventListener\FrontendSalesDocumentDatagridListener:
        arguments:
            - '@security.token_storage'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.after.frontend-sales-documents-grid, method: onBuildAfter }
            
    acme_sales_document.layout.data_provider.sales_document_dashboard:
        class: Acme\Bundle\SalesDocumentBundle\Layout\DataProvider\SalesDocumentDashboardProvider
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@oro_security.token_accessor'
            - '@oro_currency.config.currency'
            - '@oro_locale.formatter.number'
        tags:
            - { name: layout.data_provider, alias: sales_document_dashboard }
            
    acme_sales_document.layout.data_provider.scorecard:
        class: Acme\Bundle\SalesDocumentBundle\Layout\DataProvider\ScorecardDataProvider
        arguments:
            - '@acme_sales_document.layout.data_provider.sales_document_dashboard'
            - '@oro_security.token_accessor'
            - '@oro_currency.config.currency'
            - '@oro_locale.formatter.number'
        tags:
            - { name: layout.data_provider, alias: sales_document_scorecard }
            
    acme_sales_document.provider.scorecard.unpaid_invoices:
        class: Acme\Bundle\SalesDocumentBundle\ContentWidget\Provider\UnpaidInvoicesScorecardProvider
        arguments:
            - '@doctrine'
            - '@oro_security.token_accessor'
            - '@security.authorization_checker'
            - '@oro_pricing.user_currency_manager'
            - '@oro_locale.formatter.number'
            - '@oro_currency.rounding.price_rounding_service'
        tags:
            - { name: oro_commerce.scorecard }
            
    acme_sales_document.provider.scorecard.balance:
        class: Acme\Bundle\SalesDocumentBundle\ContentWidget\Provider\BalanceScorecardProvider
        arguments:
            - '@doctrine'
            - '@oro_security.token_accessor'
            - '@security.authorization_checker'
            - '@oro_pricing.user_currency_manager'
            - '@oro_locale.formatter.number'
            - '@oro_currency.rounding.price_rounding_service'
        tags:
            - { name: oro_commerce.scorecard }
            
    acme_sales_document.provider.scorecard.overdue:
        class: Acme\Bundle\SalesDocumentBundle\ContentWidget\Provider\OverdueScorecardProvider
        arguments:
            - '@doctrine'
            - '@oro_security.token_accessor'
            - '@security.authorization_checker'
            - '@oro_pricing.user_currency_manager'
            - '@oro_locale.formatter.number'
            - '@oro_currency.rounding.price_rounding_service'
        tags:
            - { name: oro_commerce.scorecard }
